"""Batch-schedule a content calendar using Meta's native scheduled_publish_time.

No always-on process required: each entry is generated by Claude once and
handed to Facebook, which publishes it at the requested time server-side.
"""
import json
from datetime import datetime
from typing import Optional

import config
from content_generator import ContentGenerator
from meta_client import MetaClient


def load_plan() -> list[dict]:
    if not config.CONTENT_PLAN_PATH.exists():
        return []
    return json.loads(config.CONTENT_PLAN_PATH.read_text(encoding="utf-8"))


def save_plan(plan: list[dict]) -> None:
    config.DATA_DIR.mkdir(exist_ok=True)
    config.CONTENT_PLAN_PATH.write_text(
        json.dumps(plan, ensure_ascii=False, indent=2), encoding="utf-8"
    )


def schedule_batch(
    entries: list[dict],
    generator: Optional[ContentGenerator] = None,
    client: Optional[MetaClient] = None,
) -> list[dict]:
    """entries: [{"topic": str, "publish_time": ...}] or [{"message": str, "publish_time": ...}]"""
    client = client or MetaClient()
    plan = load_plan()
    for entry in entries:
        publish_dt = datetime.fromisoformat(entry["publish_time"])
        if entry.get("message"):
            message = entry["message"]
        else:
            generator = generator or ContentGenerator()
            message = generator.generate_post(entry["topic"])
        result = client.schedule_post(message, publish_dt)
        plan.append(
            {
                "topic": entry.get("topic"),
                "publish_time": entry["publish_time"],
                "message": message,
                "post_id": result.get("id"),
                "status": "scheduled",
            }
        )
    save_plan(plan)
    return plan
